
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 17 22:03:13 CST 2016
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 6;
  public static final int PCOMA = 4;
  public static final int SUMA = 2;
  public static final int DECLARA = 8;
  public static final int EOF = 0;
  public static final int ID = 7;
  public static final int IGUAL = 5;
  public static final int error = 1;
  public static final int RESTA = 3;
}

