
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 18 05:45:35 CST 2016
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 38;
  public static final int TDECIMAL = 45;
  public static final int TMOD = 26;
  public static final int OPERACION = 25;
  public static final int COMAS = 23;
  public static final int NAMEARCHIVO = 48;
  public static final int TINCLUDE = 43;
  public static final int TWHILE = 11;
  public static final int ANS = 40;
  public static final int FUNCION = 2;
  public static final int MAYQ = 33;
  public static final int PARENTESISI = 28;
  public static final int DECREMENTAR = 17;
  public static final int PARENTESISD = 29;
  public static final int TFOREACH = 13;
  public static final int INCREMENTAR = 16;
  public static final int CONDITIONSYM = 32;
  public static final int MENQ = 34;
  public static final int TPRINT = 18;
  public static final int DIRECTIVA = 47;
  public static final int ITERAR = 12;
  public static final int ID = 46;
  public static final int RETORNO = 6;
  public static final int EOF = 0;
  public static final int ENCCOD = 8;
  public static final int RELACIONAL = 35;
  public static final int COMILLAS = 37;
  public static final int error = 1;
  public static final int TIPODATO = 5;
  public static final int TOR = 15;
  public static final int ASIGNACION = 3;
  public static final int ARITMETICA = 42;
  public static final int ENCVAR = 7;
  public static final int TIF = 20;
  public static final int TELSE = 22;
  public static final int PUNTO = 24;
  public static final int IDENTACION = 39;
  public static final int TFOR = 10;
  public static final int TAND = 14;
  public static final int SALTOLINEA = 44;
  public static final int TTHEN = 21;
  public static final int CORI = 30;
  public static final int ESTADISTICA = 41;
  public static final int TOPEN = 19;
  public static final int ENCFILE = 9;
  public static final int FINLINEA = 36;
  public static final int CORD = 31;
  public static final int SALIDA = 4;
  public static final int TEXP = 27;
}

